---
- name: Install prerequisites
  block:
    - name: Install unzip if unzip is absent
      package:
        name: unzip
        state: present

- name: Fetch latest run_id from the given build_type
  block:
    - name: Fetch latest run_id from the given build_type
      github_workflow_run:
        owner: juicity
        repo: juicity
        build_type: "{{ build_type }}"
      delegate_to: localhost
      register: result
      become: false
    - name: Extract run_id from outputs
      set_fact:
        run_id: "{{ result.run_id }}"
  when:
    - build_type is defined
    - latest
    - action_url is not defined

- name: Extract run_id from action_url
  set_fact:
    run_id: "{{ action_url | split('/') | last }}"
  when:
    - action_url is defined
    - build_type == "custom"

- name: Download binary from GitHub Actions
  get_url:
    url: "{{ base_url }}/{{ run_id }}/juicity-linux-x86_64.zip"
    dest: /tmp/juicity.zip
  register: download

- name: unzip juicity.zip
  unarchive:
    remote_src: yes
    src: /tmp/juicity.zip
    dest: /tmp

- name: Copy binary
  copy:
    remote_src: yes
    src: /tmp/juicity-server
    dest: /usr/bin/juicity-server
    mode: a+x

- name: Restart systemd service
  systemd:
    name: "{{ systemd_service }}"
    state: restarted
  when: download.changed

- name: Verify version
  block:
    - name: Verify version
      shell: |
        juicity-server --version
      register: version
    - name: Print output
      debug:
        msg: "{{ version.stdout }}"
  when: download.changed

